minecraft_dependency=>=26.1 <26.2
minecraft_version=26.1

# https://fabricmc.net/develop/
fabric_version=0.144.3+26.1

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.28.8
litematica=0.27.9
tweakeroo=0.28.0
malilib_artifact=malilib-fabric-26.1.2
litematica_artifact=litematica-fabric-26.1.2
tweakeroo_artifact=tweakeroo-fabric-26.1

# https://modrinth.com/mod/modmenu/versions
# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu=18.0.0-alpha.8

quickshulker=https://github.com/EnderPhantomWing/quickshulker-multi/releases/download/3.2.2/quickshulker-v3.2.2-mc26.1.jar

chesttracker=https://github.com/ponuing/ChestTracker/releases/download/v2.8.3%2B26.1.2/chesttracker-2.8.3%2B26.1.2.jar

# https://modrinth.com/mod/modmenu/versions
