minecraft_dependency=1.21.5
minecraft_version=1.21.5

# https://fabricmc.net/develop/
fabric_version=0.121.0+1.21.5

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.24.3
litematica=0.22.5
tweakeroo=0.24.3
malilib_artifact=malilib-fabric-1.21.5
litematica_artifact=litematica-fabric-1.21.5
tweakeroo_artifact=tweakeroo-fabric-1.21.5

# https://modrinth.com/mod/modmenu/versions
modmenu=14.0.1

quickshulker=https://github.com/MoRanpcy/quickshulker/releases/download/2.4.3-1.21.5/quickshulker-2.4.3-1.21.5.jar

chesttracker=https://github.com/ponuing/ChestTracker/releases/download/v2.8.3%2B1.21.5/chesttracker-2.8.3%2B1.21.5.jar

