minecraft_dependency=>=1.21.6 <=1.21.8
minecraft_version=1.21.6

# https://fabricmc.net/develop/
fabric_version=0.128.1+1.21.6

# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/malilib
# https://modrinth.com/mod/tweakeroo
# https://modrinth.com/mod/litematica
# https://jitpack.io/#sakura-ryoko/malilib
# https://jitpack.io/#sakura-ryoko/tweakeroo
# https://jitpack.io/#sakura-ryoko/litematica
malilib=0.25.7
litematica=0.23.7
tweakeroo=0.25.6
malilib_artifact=malilib-fabric-1.21.8
litematica_artifact=litematica-fabric-1.21.8
tweakeroo_artifact=tweakeroo-fabric-1.21.8

# https://modrinth.com/mod/modmenu/versions
modmenu=15.0.1

quickshulker=https://github.com/MoRanpcy/quickshulker/releases/download/2.5.2-1.21.6/quickshulker-2.5.2-1.21.6.jar

chesttracker=https://github.com/ponuing/ChestTracker/releases/download/v2.8.3%2B1.21.6/chesttracker-2.8.3%2B1.21.6.jar

